name: resellio
description: "IO2 - Resellio"
publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0

flutter:
  uses-material-design: true