name: resellio
description: "IO2 - Resellio"
publish_to: 'none'

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0

flutter:
  uses-material-design: true