name: resellio
description: "IO2 - Resellio"
publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.8.2
  leancode_lint: ^15.0.0

flutter:
  uses-material-design: true