name: resellio
description: "IO2 - Resellio"
publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  bloc_presentation: ^1.1.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^2.0.6
  go_router: ^14.8.1
  google_sign_in: ^6.3.0
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.8.2
  json_serializable: ^6.6.0
  leancode_lint: ^15.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/google.png
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
